##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

SRC     =       *.c

FILES   =       *.o

NAME    =       libmy.a

all:    $(NAME)

$(NAME): 
	gcc -c $(SRC)
	ar rc $(NAME) $(FILES)

clean:
	rm -f $(FILES)
